# Generated by Django 2.2.5 on 2020-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_ID', models.IntegerField(default=1)),
                ('station_name', models.CharField(max_length=256)),
            ],
        ),
    ]
