# Generated by Django 2.2.5 on 2020-11-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
