# Generated by Django 2.2.5 on 2020-11-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainID', models.IntegerField()),
                ('arrivalTime', models.DateTimeField()),
                ('departureTime', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Station')),
            ],
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
