# Generated by Django 2.2.5 on 2020-11-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20201126_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mumbai',
            new_name='Bhopal_Train',
        ),
        migrations.CreateModel(
            name='Mumbai_Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainID', models.IntegerField()),
                ('arrivalTime', models.DateTimeField()),
                ('departureTime', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Hyderabad_Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainID', models.IntegerField()),
                ('arrivalTime', models.DateTimeField()),
                ('departureTime', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Delhi_Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainID', models.IntegerField()),
                ('arrivalTime', models.DateTimeField()),
                ('departureTime', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Chennai_Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainID', models.IntegerField()),
                ('arrivalTime', models.DateTimeField()),
                ('departureTime', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Station')),
            ],
        ),
    ]
